// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Notifier is an autogenerated mock type for the Notifier type
type Notifier struct {
	mock.Mock
}

// SendMessage provides a mock function with given fields: content
func (_m *Notifier) SendMessage(content string) error {
	ret := _m.Called(content)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
